create table if not exists users (
    id bigint generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    email varchar(255) not null unique,
    active boolean not null default true,
    created_at timestamp not null,
    updated_at timestamp not null
);